apiVersion: secrets-store.csi.x-k8s.io/v1alpha1
kind: SecretProviderClass
metadata:
  name: csi-secret-test
  namespace: csi-secrets
spec:
  provider: gcp
  parameters:
    secrets: |
      - resourceName: "projects/195719899311/secrets/csi-secret-test/versions/1"
